troiswa_back_categorie:
    path:     /
    defaults: { _controller: TroiswaBackBundle:Categorie:index }

troiswa_back_categorie_show:
    path:     /{id}
    defaults: { _controller: TroiswaBackBundle:Categorie:show }
    requirements:
        id : \d+
        #id: "[0-9]+"

troiswa_back_categorie_create:
    path:     /create
    defaults: { _controller: TroiswaBackBundle:Categorie:create }

troiswa_back_categorie_edit:
    path:     /edit/{id}
    defaults: { _controller: TroiswaBackBundle:Categorie:edit }
    requirements:
            id : \d+

troiswa_back_categorie_delete:
    path:     /delete/{id}
    defaults: { _controller: TroiswaBackBundle:Categorie:delete }
    requirements:
            id : \d+

