troiswa_back_marque:
    resource: "@TroiswaBackBundle/Resources/config/Routing/marque.yml"
    prefix:   /marque

troiswa_back_homepage:
    path:     /hello/{name}
    defaults: { _controller: TroiswaBackBundle:Default:index }

troiswa_back_page_contact:
    path:     /contact
    defaults: { _controller: TroiswaBackBundle:Main:contact }

troiswa_back_about:
    path:     /about
    defaults: { _controller: TroiswaBackBundle:Main:about }

troiswa_back_etudiant:
    path:     /etudiant/{prenom}/{nom}
    defaults: { _controller: TroiswaBackBundle:Main:etudiant }

troiswa_back_admin:
    path:     /
    defaults: { _controller: TroiswaBackBundle:Main:admin }

troiswa_back_page_feedback:
    path:     /feedback
    defaults: { _controller: TroiswaBackBundle:Main:feedback }

troiswa_back_resource_product:
    resource: "@TroiswaBackBundle/Resources/config/Routing/product.yml"
    prefix: /product

troiswa_back_resource_categorie:
    resource: "@TroiswaBackBundle/Resources/config/Routing/categorie.yml"
    prefix: /categorie

troiswa_back_commentaire:
    path:   /commentaire
    defaults: { _controller: TroiswaBackBundle:Commentaire:index }

troiswa_back_commentaire_active:
    path:     /active/{id}
    defaults: { _controller: TroiswaBackBundle:Commentaire:active}
    requirements:
                id : \d+


troiswa_back_tag:
    resource: "@TroiswaBackBundle/Resources/config/Routing/tag.yml"
    prefix:   /tag

troiswa_back_panier:
    path:     /panier
    defaults: { _controller: TroiswaBackBundle:Cart:panier}

troiswa_back_panier_produit:
    path:     /panier/{id}
    defaults: { _controller: TroiswaBackBundle:Cart:add}
    requirements:
                id : \d+

troiswa_back_panier_produit_supprimer:
    path:     /panier/supprimer/{id}
    defaults: { _controller: TroiswaBackBundle:Cart:delete}
    requirements:
                id : \d+

troiswa_back_login:
    path: /login
    defaults: { _controller:TroiswaBackBundle:Main:login }

troiswa_back_login_check:
    path: /login_check

troiswa_back_logout:
    path: /logout

troiswa_back_register:
    path: /register
    defaults: { _controller:TroiswaBackBundle:User:create }