parameters:
 competences:
  php: 1
  html: 9
  css: 4

services:
#    troiswa_back.example:
#        class: Troiswa\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  # mon premier service
  troiswa_back.util:
    class: Troiswa\BackBundle\Util\Utility
    arguments: [%competences%, @doctrine.orm.entity_manager, "ceci est du texte"]

  troiswa_back.cart:
    class: Troiswa\BackBundle\Util\Cart
    arguments: [@doctrine.orm.entity_manager, @session]
