parameters:
 competences:
  php: 1
  html: 9
  css: 4
 genders:
  0: Homme
  1: Femme
  2: Bébé

services:
#    troiswa_back.example:
#        class: Troiswa\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  # mon premier service
  troiswa_back.util:
    class: Troiswa\BackBundle\Util\Utility
    arguments: [%competences%, @doctrine.orm.entity_manager, "ceci est du texte"]

  troiswa_back.cart:
    class: Troiswa\BackBundle\Util\Cart
    arguments: [@doctrine.orm.entity_manager, @session]

  troiswa.validator.position.category:
    class: Troiswa\BackBundle\Validator\PositionCategoryValidator
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: validator.constraint_validator, alias: troiswa_back_position_category }

  troiswa.type.gendertype:
    class: Troiswa\BackBundle\Form\Type\GenderType
    arguments: [%genders%]
    tags:
      - { name: form.type, alias: gender }

  troiswa.maintenance:
    class: Troiswa\BackBundle\Listener\Maintenance
    arguments: [@twig,%maintenance%, %kernel.environment%]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: miseEnMaintenance }