<?php

namespace Troiswa\BackBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    // Afficher le nombre de catégorie
    public function findNbCategory()
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT COUNT(cat.id)
            FROM TroiswaBackBundle:Categorie cat"
        );

        return $query->getSingleScalarResult();
    }

    // Afficher le nombre de catégorie actif
    public function findNbCategoryActif()
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT COUNT(cat.id)
            FROM TroiswaBackBundle:Categorie cat
            WHERE cat.active = 1"
        );

        return $query->getSingleScalarResult();
    }

    // Afficher le nombre de catégorie actif et inactif
    public function findNbCategoryActifInactif()
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT COUNT(cat.id), cat.active
            FROM TroiswaBackBundle:Categorie cat
            GROUP BY cat.active"
            );

        return $query->getScalarResult();
    }

    // Afficher les catégories dont la position est supérieur à 2
    public function findCategoryPosition($position = 2)
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT cat
            FROM TroiswaBackBundle:Categorie cat
            WHERE cat.position > :pos"
            )->setParameter('pos', $position);

        return $query->getResult();
    }

    public function builderCategoryOrderPosition()
    {
        return $this->createQueryBuilder('cat')
            ->orderBy('cat.position');
    }
}
